-- Production TAC -> phone mapping for the existing Supabase catalog.
-- SAFE BY DESIGN:
--   * never invents TACs
--   * only maps currently-unmapped rows
--   * requires a unique canonical phone candidate
--   * exact normalized model matches only
--   * brand must agree with the canonical phone brand
--   * leaves ambiguous/unresolved rows untouched
-- Result-page/UI files are not involved.

BEGIN;

CREATE OR REPLACE FUNCTION public.normalize_device_identity(value text)
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$
  SELECT trim(regexp_replace(lower(coalesce(value, '')), '[^a-z0-9]+', ' ', 'g'));
$$;

CREATE INDEX IF NOT EXISTS idx_tac_allocations_phone_id ON public.tac_allocations(phone_id);
CREATE INDEX IF NOT EXISTS idx_tac_allocations_brand_id ON public.tac_allocations(brand_id);
CREATE INDEX IF NOT EXISTS idx_tac_allocations_reported_brand_norm ON public.tac_allocations(public.normalize_device_identity(reported_brand));
CREATE INDEX IF NOT EXISTS idx_tac_allocations_reported_model_norm ON public.tac_allocations(public.normalize_device_identity(reported_model_name));
CREATE INDEX IF NOT EXISTS idx_phones_brand_model_norm ON public.phones(brand_id, public.normalize_device_identity(model_name));
CREATE INDEX IF NOT EXISTS idx_brands_name_norm ON public.brands(public.normalize_device_identity(name));

CREATE TABLE IF NOT EXISTS public.tac_mapping_audit (
  audit_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tac_id bigint NOT NULL,
  tac varchar NOT NULL,
  old_phone_id integer,
  new_phone_id integer NOT NULL,
  old_brand_id integer,
  new_brand_id integer NOT NULL,
  mapping_method text NOT NULL,
  previous_status text,
  previous_confidence numeric,
  mapped_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tac_id, new_phone_id, mapping_method)
);

CREATE TEMP TABLE _brand_alias(alias_norm text PRIMARY KEY, canonical_norm text NOT NULL) ON COMMIT DROP;
INSERT INTO _brand_alias(alias_norm, canonical_norm) VALUES
  ('apple','apple'),('samsung','samsung'),('xiaomi','xiaomi'),('redmi','xiaomi'),('poco','xiaomi'),
  ('oppo','oppo'),('realme','realme'),('vivo','vivo'),('oneplus','oneplus'),('google','google'),
  ('motorola','motorola'),('nokia','nokia'),('huawei','huawei'),('honor','honor'),('sony','sony'),
  ('lg','lg'),('htc','htc'),('zte','zte'),('tecno','tecno'),('infinix','infinix'),('itel','itel'),
  ('asus','asus'),('lenovo','lenovo'),('alcatel','alcatel'),('tcl','tcl'),('blu','blu');

CREATE TEMP TABLE _brand_candidates ON COMMIT DROP AS
SELECT t.tac_id, min(b.brand_id) AS brand_id, count(DISTINCT b.brand_id) AS candidate_count
FROM public.tac_allocations t
JOIN _brand_alias a ON a.alias_norm = public.normalize_device_identity(t.reported_brand)
JOIN public.brands b ON public.normalize_device_identity(b.name) = a.canonical_norm
WHERE t.phone_id IS NULL
GROUP BY t.tac_id;
CREATE INDEX ON _brand_candidates(tac_id);

UPDATE public.tac_allocations t
SET brand_id = bc.brand_id, updated_at = now()
FROM _brand_candidates bc
WHERE t.tac_id = bc.tac_id AND t.brand_id IS NULL AND bc.candidate_count = 1;

CREATE TEMP TABLE _exact_candidates ON COMMIT DROP AS
SELECT t.tac_id, min(p.phone_id) AS phone_id, min(p.brand_id) AS brand_id,
       count(DISTINCT p.phone_id) AS candidate_count
FROM public.tac_allocations t
JOIN public.phones p
  ON p.brand_id = t.brand_id
 AND public.normalize_device_identity(p.model_name) = public.normalize_device_identity(t.reported_model_name)
WHERE t.phone_id IS NULL
  AND t.brand_id IS NOT NULL
  AND nullif(public.normalize_device_identity(t.reported_model_name), '') IS NOT NULL
GROUP BY t.tac_id;
CREATE INDEX ON _exact_candidates(tac_id);

INSERT INTO public.tac_mapping_audit
  (tac_id, tac, old_phone_id, new_phone_id, old_brand_id, new_brand_id,
   mapping_method, previous_status, previous_confidence)
SELECT t.tac_id, t.tac, t.phone_id, c.phone_id, t.brand_id, c.brand_id,
       'exact_normalized_brand_model', t.match_status, t.match_confidence
FROM public.tac_allocations t
JOIN _exact_candidates c ON c.tac_id = t.tac_id
WHERE t.phone_id IS NULL AND c.candidate_count = 1
ON CONFLICT DO NOTHING;

-- Production constraint permits: unmatched, auto_matched, manual_matched, ambiguous, ignored.
-- These are deterministic automatic matches, so auto_matched is the correct status.
UPDATE public.tac_allocations t
SET phone_id = c.phone_id,
    brand_id = c.brand_id,
    match_status = 'auto_matched',
    match_confidence = GREATEST(coalesce(t.match_confidence, 0), 0.95),
    updated_at = now()
FROM _exact_candidates c
WHERE t.tac_id = c.tac_id AND t.phone_id IS NULL AND c.candidate_count = 1;

UPDATE public.tac_allocations
SET reported_year = NULL, updated_at = now()
WHERE reported_year IS NOT NULL
  AND (reported_year < 1980 OR reported_year > extract(year FROM CURRENT_DATE)::int + 1);

-- Second conservative pass: exact normalized reported model where the model
-- exists exactly once in the catalog. Brand evidence must either agree or be absent.
CREATE TEMP TABLE _global_exact_candidates ON COMMIT DROP AS
SELECT
  t.tac_id,
  min(p.phone_id) AS phone_id,
  min(p.brand_id) AS brand_id,
  count(DISTINCT p.phone_id) AS candidate_count
FROM public.tac_allocations t
JOIN public.phones p
  ON public.normalize_device_identity(p.model_name) =
     public.normalize_device_identity(t.reported_model_name)
LEFT JOIN public.brands pb ON pb.brand_id = p.brand_id
WHERE t.phone_id IS NULL
  AND nullif(public.normalize_device_identity(t.reported_model_name), '') IS NOT NULL
  AND (
    nullif(public.normalize_device_identity(t.reported_brand), '') IS NULL
    OR public.normalize_device_identity(t.reported_brand) = public.normalize_device_identity(pb.name)
    OR EXISTS (
      SELECT 1 FROM _brand_alias a
      WHERE a.alias_norm = public.normalize_device_identity(t.reported_brand)
        AND a.canonical_norm = public.normalize_device_identity(pb.name)
    )
  )
GROUP BY t.tac_id;
CREATE INDEX ON _global_exact_candidates(tac_id);

INSERT INTO public.tac_mapping_audit
  (tac_id, tac, old_phone_id, new_phone_id, old_brand_id, new_brand_id,
   mapping_method, previous_status, previous_confidence)
SELECT t.tac_id, t.tac, t.phone_id, c.phone_id, t.brand_id, c.brand_id,
       'unique_exact_model_identity', t.match_status, t.match_confidence
FROM public.tac_allocations t
JOIN _global_exact_candidates c ON c.tac_id = t.tac_id
WHERE t.phone_id IS NULL AND c.candidate_count = 1
ON CONFLICT DO NOTHING;

UPDATE public.tac_allocations t
SET phone_id = c.phone_id,
    brand_id = coalesce(t.brand_id, c.brand_id),
    match_status = 'auto_matched',
    match_confidence = GREATEST(coalesce(t.match_confidence, 0), 0.90),
    updated_at = now()
FROM _global_exact_candidates c
WHERE t.tac_id = c.tac_id
  AND t.phone_id IS NULL
  AND c.candidate_count = 1;

COMMIT;

SELECT
  count(*) AS total_tacs,
  count(*) FILTER (WHERE phone_id IS NOT NULL) AS mapped_tacs,
  count(*) FILTER (WHERE phone_id IS NULL) AS unmapped_tacs,
  round(100.0 * count(*) FILTER (WHERE phone_id IS NOT NULL) / nullif(count(*),0), 2) AS mapped_percent,
  count(*) FILTER (WHERE match_status = 'auto_matched') AS auto_matched_rows,
  count(*) FILTER (WHERE match_status = 'manual_matched') AS manual_matched_rows,
  count(*) FILTER (WHERE match_status = 'ambiguous') AS ambiguous_rows
FROM public.tac_allocations;

SELECT mapping_method, count(*) AS newly_mapped
FROM public.tac_mapping_audit
GROUP BY mapping_method
ORDER BY newly_mapped DESC;
