"use client";
import Link from "next/link";
import {useState} from "react";
import {lookupPublicImei} from "./lib/api";
const services=[
["fa-ban","Blacklist & Status Check","Review status information available from the connected IMEI data sources."],
["fa-sim-card","Carrier & SIM-Lock Information","Explore carrier and network information available for supported devices."],
["fa-cloud","Device & Activation Data","Resolve device identity and the records currently available in our database."],
["fa-microchip","Hardware Spec & TAC Decoder","Decode the TAC and explore matched hardware specifications."],
["fa-clock-rotate-left","Device Database History","Browse model, release and specification data stored in the phone catalog."],
["fa-database","IMEI & Device Intelligence","Connect an IMEI lookup to the matching phone record when a match exists."]
];
const faqs=[
["What is an IMEI number and why is it unique?","An IMEI is a 15-digit identifier used for mobile equipment. The first eight digits form the TAC and the final digit is a check digit."],
["How can I find my IMEI if the phone screen is broken?","The IMEI may also appear on original packaging, purchase documentation or a device label, depending on the manufacturer."],
["Is it safe to share or check my IMEI number online?","Avoid publishing a full IMEI publicly. Use it only with services or people that genuinely need it."],
["What is the difference between an IMEI, MEID, and Serial Number?","They are different identifiers. IMEI identifies cellular equipment, while serial numbers are manufacturer identifiers."],
["Can a blacklisted phone be unlocked or cleared?","Blacklist and ownership issues should be resolved through the relevant carrier, seller or authorized service."],
["How current is the device information?","Results depend on the records available in the project's connected databases and can vary by device."]
];
export default function Home(){
 const[imei,setImei]=useState("");const[error,setError]=useState("");
 async function check(e){e.preventDefault();const v=imei.replace(/\D/g,"");if(v.length!==15){setError("Enter a valid 15-digit IMEI number.");return}setError("");try{const r=await lookupPublicImei(v);if(!r?.success){setError(r?.error||"IMEI lookup failed.");return}window.location.href="/results/"+v}catch{setError("Something went wrong.")}}
 return <div className="st-home">
 <section className="st-hero"><div className="st-container"><div className="st-signal"><i className="fas fa-circle-check"/> DEVICE INTELLIGENCE <b>• Instant TAC Lookup</b></div><div className="st-hero-grid">
 <div className="st-copy"><h1>Check Your Device.<br/><span>Know Exactly</span> What<br/>You're Buying.</h1><p>Instant device identity and specification lookup using the IMEI and TAC records available in our platform. Check a device before you buy, sell or troubleshoot it.</p>
 <form className="st-checker" onSubmit={check}><div className="st-input"><i className="fas fa-mobile-screen-button"/><input value={imei} onChange={e=>setImei(e.target.value.replace(/\D/g,"").slice(0,15))} inputMode="numeric" placeholder="Enter 15-digit IMEI number"/><span>{imei.length}/15</span></div><button>CHECK IMEI NOW <i className="fas fa-arrow-right"/></button></form>{error&&<div className="st-error"><i className="fas fa-circle-exclamation"/> {error}</div>}
 <div className="st-trust"><span><i className="fas fa-circle-check"/>15-digit validation</span><span><i className="fas fa-bolt"/>Instant carrier/device lookup</span><span><i className="fas fa-database"/>TAC-based matching</span><span><i className="fas fa-lock"/>Privacy focused</span></div></div>
 <div className="st-console"><div className="st-console-head"><span>● TAC INSPECTION ENGINE</span><span>READY</span></div><div className="st-phone-outline"><div className="st-scan"/></div><div className="st-hud st-hud-a"><b>IMEI STRUCTURE</b>15 digits detected<br/>TAC + serial + check digit</div><div className="st-console-center"><i className="fas fa-mobile-screen-button"/>DEVICE IDENTITY<br/><span>READY FOR LOOKUP</span></div><div className="st-hud st-hud-b"><b>DATABASE RESOLUTION</b>Brand / model / specs<br/>when records match</div></div>
 </div></div></section>
 <section className="st-stats"><div className="st-container st-stats-grid"><div className="st-stat"><strong>254,980</strong><span>TAC records in current dataset</span><small>Database coverage</small></div><div className="st-stat"><strong>34,563</strong><span>TACs currently mapped</span><small>Layer 1 complete</small></div><div className="st-stat"><strong>15</strong><span>Digits in a standard IMEI</span><small>Structure validation</small></div><div className="st-stat"><strong>8</strong><span>Digits in the TAC</span><small>Device allocation code</small></div></div></section>
 <section className="st-section"><div className="st-container"><div className="st-section-head"><span className="st-eyebrow">VERIFICATION PIPELINE</span><h2>How Our IMEI Lookup Operates</h2><p>From a single 15-digit IMEI to a structured device result using the data currently connected to this project.</p></div><div className="st-three">{[["01","fa-keyboard","Locate Your IMEI","Dial *#06# or use your device settings, packaging or purchase documentation."],["02","fa-fingerprint","Validate & Decode","The checker validates the number format and extracts the eight-digit TAC."],["03","fa-file-lines","Get the Device Report","When a TAC is mapped, the result connects to brand, model, specifications and verified media."]].map(x=><div className="st-step" key={x[0]}><div className="st-step-top"><span>PHASE {x[0]}</span><i className="fas fa-grip"/></div><div className="st-step-icon"><i className={"fas "+x[1]}/></div><h3>{x[2]}</h3><p>{x[3]}</p></div>)}</div></div></section>
 <section className="st-section soft"><div className="st-container"><div className="st-split-head"><div><span className="st-eyebrow">CAPABILITIES</span><h2>Specialized Device Intelligence</h2></div><p>Tools built around the records and features available in this project.</p></div><div className="st-service-grid">{services.map((s,i)=><div className="st-service" key={s[1]}><div className="st-service-icon"><i className={"fas "+s[0]}/></div><h3>{s[1]}</h3><p>{s[2]}</p><Link href={i===3?"/phones":i===1?"/carriers":"/"}>Explore <i className="fas fa-arrow-right"/></Link></div>)}</div></div></section>
 <section className="st-section"><div className="st-container"><div className="st-section-head"><span className="st-eyebrow">DEVICE DATA PREVIEW</span><h2>What an IMEI Check Can Unlock</h2><p>A matched TAC can connect the lookup to structured phone information already stored by the platform.</p></div><div className="st-preview"><div className="st-preview-tabs"><span>Hardware Specifications</span><span>Carrier & Network</span><span>Device Identity</span><span>Available Media</span></div><div className="st-preview-grid">{[["DEVICE IDENTITY","Brand + Model","Resolved from mapped TAC"],["TAC ALLOCATION","First 8 IMEI digits","Type Allocation Code"],["DISPLAY","Screen specifications","When catalogued"],["PLATFORM","Chipset / processor","When catalogued"],["CAMERA","Main camera details","When catalogued"],["BATTERY","Capacity information","When catalogued"]].map(x=><div className="st-spec" key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong><small>{x[2]}</small></div>)}</div></div></div></section>
 <section className="st-section soft"><div className="st-container"><div className="st-alert"><div><span className="st-eyebrow" style={{color:"#f87171"}}>BUYER AWARENESS</span><h2>Buying Used? Verify the Device Before You Pay.</h2><p>Compare the returned identity and specifications with the physical phone, seller information and purchase documentation. An IMEI lookup is one useful part of a broader used-device inspection.</p><Link href="#top" className="st-btn">Run IMEI Check</Link></div><div className="st-alert-box"><div className="st-alert-row red">● IDENTITY MISMATCH<br/>Returned model differs from the device</div><div className="st-alert-row green">● CONSISTENT DEVICE DATA<br/>Identity and specifications align</div><small style={{color:"#64748b"}}>Always verify ownership and condition separately.</small></div></div></div></section>
 <section className="st-section"><div className="st-container"><div className="st-split-head"><div><span className="st-eyebrow">FIELD KNOWLEDGE</span><h2>Device Intelligence Guides</h2></div><Link href="/news">Browse guides →</Link></div><div className="st-guide-grid">{[["fa-mobile-screen","How to Find Your IMEI on Any Phone","Learn the common ways to locate a device IMEI."],["fa-list-check","The Used-Phone Pre-Purchase Checklist","What to compare before paying for a second-hand phone."],["fa-qrcode","What Is a TAC Number?","Understand the first eight digits of an IMEI and what they represent."]].map((g,i)=><div className="st-guide" key={g[1]}><div className="st-guide-art"><i className={"fas "+g[0]}/></div><div className="st-guide-body"><small className="st-eyebrow">GUIDE</small><h3>{g[1]}</h3><p>{g[2]}</p><Link href={i===2?"/faq":"/news"}>Read guide →</Link></div></div>)}</div></div></section>
 <section className="st-section soft"><div className="st-container"><div className="st-section-head"><span className="st-eyebrow">ANSWERS & FACTS</span><h2>Frequently Asked Questions</h2><p>Everything you need to know about IMEI identity and this project's lookup tools.</p></div><div className="st-faq">{faqs.map((f,i)=><details key={f[0]} open={i===0}><summary>{f[0]}</summary><p>{f[1]}</p></details>)}</div></div></section>
 <section className="st-section"><div className="st-container"><div className="st-final"><span className="st-eyebrow">INSTANT IMEI LOOKUP</span><h2>Know Your Device Before You Pay.</h2><p>Enter a 15-digit IMEI to inspect the records currently available for that device.</p><form className="st-checker" onSubmit={check}><div className="st-input"><input value={imei} onChange={e=>setImei(e.target.value.replace(/\D/g,"").slice(0,15))} placeholder="Type 15-digit IMEI to verify..."/></div><button>Check Device Now</button></form></div></div></section>
 </div>
